// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DoSnkwv3DRrQvKTLh6-nyQIWiYJUQyI',
    appId: '1:909859028390:android:9e1fbb7474dbc8a0836367',
    messagingSenderId: '909859028390',
    projectId: 'toonies-d3ea1',
    storageBucket: 'toonies-d3ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyecegLxlSwfENDUXDs_PHT-Ur_L--DbU',
    appId: '1:909859028390:ios:a756f6ef9440fd1c836367',
    messagingSenderId: '909859028390',
    projectId: 'toonies-d3ea1',
    storageBucket: 'toonies-d3ea1.firebasestorage.app',
    iosClientId:
        '909859028390-m17s24v79fo22tm606vlb5hqil2omqj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.toonies',
  );
}
